keys:
  - &filippo_msi age18asfdry0rx3t6zzvdrpu94cyeax2595wfwegy7g7zj67egyn2alql8k9rs
  - &filippo_macbook-pro age10hekr2fzda03xna7gc9hpwcqh8yscwny2v03t94wudfuu3ylmd0q0grctk
  - &filippo_server-stella age13l6j4ahtluv83t03gqn7cd66nhmx7lgnszx87wlr8vunf8fw5v0szx4l2a
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - age:
      - *filippo_msi
      - *filippo_macbook-pro
      - *filippo_server-stella
  - path_regex: secrets/msi/secrets.yaml$
    key_groups:
    - age:
      - *filippo_msi
      - *filippo_macbook-pro
  - path_regex: secrets/server-stella/secrets.yaml$
    key_groups:
    - age:
      - *filippo_server-stella
      - *filippo_macbook-pro
